# Generated by Django 2.2 on 2021-06-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration_app', '0006_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercise',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise',
            field=models.ManyToManyField(related_name='added_exercise', to='login_and_registration_app.Exercise'),
        ),
    ]
