# Generated by Django 2.2 on 2021-06-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration_app', '0008_auto_20210630_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workouts', to='login_and_registration_app.Exercise'),
        ),
    ]
