# Generated by Django 2.2 on 2021-06-30 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration_app', '0009_auto_20210630_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='login_and_registration_app.User'),
            preserve_default=False,
        ),
    ]
