# Generated by Django 2.2 on 2021-07-02 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration_app', '0014_workout_exercises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='exercises',
            new_name='exercise',
        ),
    ]
